version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: midterm_app
    ports:
      - "8888:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/midterm_sw
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  db:
    image: postgres:15-alpine
    container_name: midterm_db
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: midterm_sw
    volumes:
      - postgres_data_simple:/var/lib/postgresql/data

volumes:
  postgres_data_simple: